version: '3.7'

services:
#  file_keeper:
#    command: 'python -u /src/app/detect-defect-app.py'
#    volumes:
#      - ./app:/src/app
#      - ./datasets:/src/datasets
#    links:
#      - postgres
#    depends_on:
#      - postgres

  postgres:
    build: ./deploy/postgres
    restart: always
#    command: 'python -u /data_operations/data_preparation.py'
    env_file:
      - ./deploy/postgres/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    ports:
      - "5438:5432"
